// Auto-generated by update_scores.py - do not hand-edit.
window.WC_DATA = {
  "updated": "2026-06-17 19:51",
  "scoring": {
    "win": 3,
    "draw": 1,
    "goalFor": 1,
    "yellow": -1,
    "red": -3,
    "multiGoalOver": 2,
    "multiGoalBonusPer": 2,
    "upsetMinGap": 10,
    "upsetTiers": [
      {
        "minGap": 50,
        "win": 12,
        "draw": 6
      },
      {
        "minGap": 25,
        "win": 8,
        "draw": 4
      },
      {
        "minGap": 10,
        "win": 4,
        "draw": 2
      }
    ]
  },
  "players": [
    {
      "id": "p1",
      "name": "Adam",
      "photo": "adam.jpg",
      "teams": [
        "NED",
        "NOR",
        "CZE",
        "JPN"
      ],
      "paid": true
    },
    {
      "id": "p2",
      "name": "Ale",
      "photo": "ale.jpg",
      "teams": [
        "POR",
        "UZB",
        "CAN",
        "NZL"
      ],
      "paid": false
    },
    {
      "id": "p3",
      "name": "Allan",
      "photo": "allan.jpg",
      "teams": [
        "BEL",
        "TUR",
        "ECU",
        "RSA"
      ],
      "paid": false
    },
    {
      "id": "p4",
      "name": "Anto",
      "photo": "anto.jpg",
      "teams": [
        "MAR",
        "SEN",
        "IRN",
        "HAI"
      ],
      "paid": true
    },
    {
      "id": "p5",
      "name": "Cleary",
      "photo": "cleary.jpg",
      "teams": [
        "BRA",
        "PAN",
        "TUN",
        "IRQ"
      ],
      "paid": true
    },
    {
      "id": "p6",
      "name": "Doc",
      "photo": "doc.jpg",
      "teams": [
        "COL",
        "KSA",
        "QAT",
        "CUW"
      ],
      "paid": true
    },
    {
      "id": "p7",
      "name": "Joey",
      "photo": "joey.jpg",
      "teams": [
        "CRO",
        "AUT",
        "KOR",
        "EGY"
      ],
      "paid": false
    },
    {
      "id": "p8",
      "name": "Molloy",
      "photo": "molloy.jpg",
      "teams": [
        "ARG",
        "USA",
        "PAR",
        "AUS"
      ],
      "paid": false
    },
    {
      "id": "p9",
      "name": "Shauna",
      "photo": "shauna.jpg",
      "teams": [
        "GER",
        "SCO",
        "CIV",
        "BIH"
      ],
      "paid": true
    },
    {
      "id": "p10",
      "name": "Suilley",
      "photo": "suilley.jpg",
      "teams": [
        "ENG",
        "GHA",
        "CPV",
        "MEX"
      ],
      "paid": true
    },
    {
      "id": "p11",
      "name": "Timmy",
      "photo": "timmy.jpg",
      "teams": [
        "FRA",
        "JOR",
        "SWE",
        "SUI"
      ],
      "paid": true
    },
    {
      "id": "p12",
      "name": "Tom",
      "photo": "tom.jpg",
      "teams": [
        "ESP",
        "COD",
        "ALG",
        "URU"
      ],
      "paid": true
    }
  ],
  "teams": {
    "MEX": {
      "name": "Mexico",
      "flag": "🇲🇽",
      "group": "A",
      "rank": 14,
      "iso": "mx"
    },
    "RSA": {
      "name": "South Africa",
      "flag": "🇿🇦",
      "group": "A",
      "rank": 60,
      "iso": "za"
    },
    "KOR": {
      "name": "South Korea",
      "flag": "🇰🇷",
      "group": "A",
      "rank": 25,
      "iso": "kr"
    },
    "CZE": {
      "name": "Czechia",
      "flag": "🇨🇿",
      "group": "A",
      "rank": 39,
      "iso": "cz"
    },
    "CAN": {
      "name": "Canada",
      "flag": "🇨🇦",
      "group": "B",
      "rank": 30,
      "iso": "ca"
    },
    "BIH": {
      "name": "Bosnia & Herz.",
      "flag": "🇧🇦",
      "group": "B",
      "rank": 64,
      "iso": "ba"
    },
    "QAT": {
      "name": "Qatar",
      "flag": "🇶🇦",
      "group": "B",
      "rank": 57,
      "iso": "qa"
    },
    "SUI": {
      "name": "Switzerland",
      "flag": "🇨🇭",
      "group": "B",
      "rank": 19,
      "iso": "ch"
    },
    "BRA": {
      "name": "Brazil",
      "flag": "🇧🇷",
      "group": "C",
      "rank": 6,
      "iso": "br"
    },
    "MAR": {
      "name": "Morocco",
      "flag": "🇲🇦",
      "group": "C",
      "rank": 8,
      "iso": "ma"
    },
    "HAI": {
      "name": "Haiti",
      "flag": "🇭🇹",
      "group": "C",
      "rank": 83,
      "iso": "ht"
    },
    "SCO": {
      "name": "Scotland",
      "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
      "group": "C",
      "rank": 42,
      "iso": "gb-sct"
    },
    "USA": {
      "name": "United States",
      "flag": "🇺🇸",
      "group": "D",
      "rank": 17,
      "iso": "us"
    },
    "PAR": {
      "name": "Paraguay",
      "flag": "🇵🇾",
      "group": "D",
      "rank": 40,
      "iso": "py"
    },
    "AUS": {
      "name": "Australia",
      "flag": "🇦🇺",
      "group": "D",
      "rank": 27,
      "iso": "au"
    },
    "TUR": {
      "name": "Turkiye",
      "flag": "🇹🇷",
      "group": "D",
      "rank": 22,
      "iso": "tr"
    },
    "GER": {
      "name": "Germany",
      "flag": "🇩🇪",
      "group": "E",
      "rank": 10,
      "iso": "de"
    },
    "CUW": {
      "name": "Curacao",
      "flag": "🇨🇼",
      "group": "E",
      "rank": 82,
      "iso": "cw"
    },
    "CIV": {
      "name": "Ivory Coast",
      "flag": "🇨🇮",
      "group": "E",
      "rank": 33,
      "iso": "ci"
    },
    "ECU": {
      "name": "Ecuador",
      "flag": "🇪🇨",
      "group": "E",
      "rank": 23,
      "iso": "ec"
    },
    "NED": {
      "name": "Netherlands",
      "flag": "🇳🇱",
      "group": "F",
      "rank": 7,
      "iso": "nl"
    },
    "JPN": {
      "name": "Japan",
      "flag": "🇯🇵",
      "group": "F",
      "rank": 18,
      "iso": "jp"
    },
    "SWE": {
      "name": "Sweden",
      "flag": "🇸🇪",
      "group": "F",
      "rank": 38,
      "iso": "se"
    },
    "TUN": {
      "name": "Tunisia",
      "flag": "🇹🇳",
      "group": "F",
      "rank": 46,
      "iso": "tn"
    },
    "BEL": {
      "name": "Belgium",
      "flag": "🇧🇪",
      "group": "G",
      "rank": 9,
      "iso": "be"
    },
    "EGY": {
      "name": "Egypt",
      "flag": "🇪🇬",
      "group": "G",
      "rank": 29,
      "iso": "eg"
    },
    "IRN": {
      "name": "Iran",
      "flag": "🇮🇷",
      "group": "G",
      "rank": 20,
      "iso": "ir"
    },
    "NZL": {
      "name": "New Zealand",
      "flag": "🇳🇿",
      "group": "G",
      "rank": 85,
      "iso": "nz"
    },
    "ESP": {
      "name": "Spain",
      "flag": "🇪🇸",
      "group": "H",
      "rank": 2,
      "iso": "es"
    },
    "CPV": {
      "name": "Cape Verde",
      "flag": "🇨🇻",
      "group": "H",
      "rank": 67,
      "iso": "cv"
    },
    "KSA": {
      "name": "Saudi Arabia",
      "flag": "🇸🇦",
      "group": "H",
      "rank": 61,
      "iso": "sa"
    },
    "URU": {
      "name": "Uruguay",
      "flag": "🇺🇾",
      "group": "H",
      "rank": 16,
      "iso": "uy"
    },
    "FRA": {
      "name": "France",
      "flag": "🇫🇷",
      "group": "I",
      "rank": 1,
      "iso": "fr"
    },
    "SEN": {
      "name": "Senegal",
      "flag": "🇸🇳",
      "group": "I",
      "rank": 15,
      "iso": "sn"
    },
    "IRQ": {
      "name": "Iraq",
      "flag": "🇮🇶",
      "group": "I",
      "rank": 56,
      "iso": "iq"
    },
    "NOR": {
      "name": "Norway",
      "flag": "🇳🇴",
      "group": "I",
      "rank": 31,
      "iso": "no"
    },
    "ARG": {
      "name": "Argentina",
      "flag": "🇦🇷",
      "group": "J",
      "rank": 3,
      "iso": "ar"
    },
    "ALG": {
      "name": "Algeria",
      "flag": "🇩🇿",
      "group": "J",
      "rank": 28,
      "iso": "dz"
    },
    "AUT": {
      "name": "Austria",
      "flag": "🇦🇹",
      "group": "J",
      "rank": 24,
      "iso": "at"
    },
    "JOR": {
      "name": "Jordan",
      "flag": "🇯🇴",
      "group": "J",
      "rank": 63,
      "iso": "jo"
    },
    "POR": {
      "name": "Portugal",
      "flag": "🇵🇹",
      "group": "K",
      "rank": 5,
      "iso": "pt"
    },
    "COD": {
      "name": "DR Congo",
      "flag": "🇨🇩",
      "group": "K",
      "rank": 45,
      "iso": "cd"
    },
    "UZB": {
      "name": "Uzbekistan",
      "flag": "🇺🇿",
      "group": "K",
      "rank": 51,
      "iso": "uz"
    },
    "COL": {
      "name": "Colombia",
      "flag": "🇨🇴",
      "group": "K",
      "rank": 13,
      "iso": "co"
    },
    "ENG": {
      "name": "England",
      "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      "group": "L",
      "rank": 4,
      "iso": "gb-eng"
    },
    "CRO": {
      "name": "Croatia",
      "flag": "🇭🇷",
      "group": "L",
      "rank": 11,
      "iso": "hr"
    },
    "GHA": {
      "name": "Ghana",
      "flag": "🇬🇭",
      "group": "L",
      "rank": 73,
      "iso": "gh"
    },
    "PAN": {
      "name": "Panama",
      "flag": "🇵🇦",
      "group": "L",
      "rank": 34,
      "iso": "pa"
    }
  },
  "matches": [
    {
      "date": "2026-06-11",
      "home": "MEX",
      "away": "RSA",
      "hs": 2,
      "as": 0,
      "hy": 1,
      "hr": 1,
      "ay": 2,
      "ar": 2,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-11",
      "home": "KOR",
      "away": "CZE",
      "hs": 2,
      "as": 1,
      "hy": 1,
      "hr": 0,
      "ay": 0,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-12",
      "home": "CAN",
      "away": "BIH",
      "hs": 1,
      "as": 1,
      "hy": 2,
      "hr": 0,
      "ay": 3,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-12",
      "home": "USA",
      "away": "PAR",
      "hs": 4,
      "as": 1,
      "hy": 1,
      "hr": 0,
      "ay": 5,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-13",
      "home": "QAT",
      "away": "SUI",
      "hs": 1,
      "as": 1,
      "hy": 2,
      "hr": 0,
      "ay": 1,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-13",
      "home": "BRA",
      "away": "MAR",
      "hs": 1,
      "as": 1,
      "hy": 2,
      "hr": 0,
      "ay": 0,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-13",
      "home": "HAI",
      "away": "SCO",
      "hs": 0,
      "as": 1,
      "hy": 1,
      "hr": 0,
      "ay": 3,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-13",
      "home": "AUS",
      "away": "TUR",
      "hs": 2,
      "as": 0,
      "hy": 0,
      "hr": 0,
      "ay": 1,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-14",
      "home": "GER",
      "away": "CUW",
      "hs": 7,
      "as": 1,
      "hy": 0,
      "hr": 0,
      "ay": 0,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-14",
      "home": "CIV",
      "away": "ECU",
      "hs": 1,
      "as": 0,
      "hy": 3,
      "hr": 0,
      "ay": 1,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-14",
      "home": "NED",
      "away": "JPN",
      "hs": 2,
      "as": 2,
      "hy": 3,
      "hr": 0,
      "ay": 0,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-14",
      "home": "SWE",
      "away": "TUN",
      "hs": 5,
      "as": 1,
      "hy": 0,
      "hr": 0,
      "ay": 1,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-15",
      "home": "BEL",
      "away": "EGY",
      "hs": 1,
      "as": 1,
      "hy": 2,
      "hr": 0,
      "ay": 2,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-15",
      "home": "IRN",
      "away": "NZL",
      "hs": 2,
      "as": 2,
      "hy": 1,
      "hr": 0,
      "ay": 0,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-15",
      "home": "ESP",
      "away": "CPV",
      "hs": 0,
      "as": 0,
      "hy": 1,
      "hr": 0,
      "ay": 1,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-15",
      "home": "KSA",
      "away": "URU",
      "hs": 1,
      "as": 1,
      "hy": 1,
      "hr": 0,
      "ay": 0,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-16",
      "home": "FRA",
      "away": "SEN",
      "hs": 3,
      "as": 1,
      "hy": 0,
      "hr": 0,
      "ay": 0,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-16",
      "home": "IRQ",
      "away": "NOR",
      "hs": 1,
      "as": 4,
      "hy": 1,
      "hr": 0,
      "ay": 0,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-16",
      "home": "ARG",
      "away": "ALG",
      "hs": 3,
      "as": 0,
      "hy": 0,
      "hr": 0,
      "ay": 0,
      "ar": 0,
      "status": "FINISHED"
    },
    {
      "date": "2026-06-16",
      "home": "AUT",
      "away": "JOR",
      "hs": 3,
      "as": 1,
      "hy": 1,
      "hr": 0,
      "ay": 0,
      "ar": 0,
      "status": "FINISHED"
    }
  ],
  "entryFee": 5,
  "prevOrder": [
    "p9",
    "p11",
    "p8",
    "p6",
    "p2",
    "p10",
    "p1",
    "p7",
    "p4",
    "p12",
    "p5",
    "p3"
  ]
};
